
#Obstacle marking parameters
obstacle_range: 2.5
max_obstacle_height: 4.0
raytrace_range: 3.0

#Robot's footprint
footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.35, 0.35],[0.35, -0.35]]


#Cost function parameters
inflation_radius: 0.5


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: sick_l, data_type: LaserScan, topic: laser_scan, marking: true, clearing: true}
